version: '3.8'
services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-development}
    image: ixyz0/learnhorizon-backend-app:latest
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - SEED_DB=${SEED_DB}
      - UPLOAD_PATH=${UPLOAD_PATH}
      - PORT=${PORT}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
      - MONGO_URI_LOCAL=${MONGO_URI_LOCAL}
      - MONGO_URI_REMOTE=${MONGO_URI_REMOTE}

    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
